# -*- coding: utf-8 -*-
"""Assignment 2 and 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrQgQbQ7FVvRjVrtBeITUgxbjEawR8Ts

ASSIGNMENT 2

1- Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a
given list of non-empty tuples.
Sample List : [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
Expected Result : [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]
"""

sl=[(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
s=sorted(sl, key=lambda x:x[1])
s

"""2- Write a Python program to get the difference between the two lists.
list1 = [1, 3, 5, 7, 9]
list2 = [1, 2, 4, 6, 7, 8]
O/P
[9, 3, 5, 8, 2, 4, 6]
"""

l1=[1, 3, 5, 7, 9]
l2=[1, 2, 4, 6, 7, 8]
s1=set(l1)
s2=set(l2)
s3=list(s1.symmetric_difference(s2))
s3

"""3- Write a Python program to find the second smallest number in a list.
EXAMPLE
[1, 2, -8, -2, 3]
O/P
-2
"""

lt=[1, 2, -8, -2, 3, 4,-5,-6,-1]
lt.sort()
lt[1]

"""4- Write a Python program to find the second smallest number in a list."""

lt=[1, 2, -8, -2, 3]
lt.sort()
lt[1]

"""5- Write a Python script to concatenate following dictionaries to create a new one.
Sample Dictionary :
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
"""

dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
d4={**dic1,**dic2,**dic3}
print(d4)

"""6- Write a Python program to sum all the items in a dictionary."""

s=0
d = {'a':1,'b':2,'c':3,'d':4}
for i in d:
  s=s+d[i]
print("Sum of all the items :",s)

"""Write a Python program to split a list every Nth element.
Sample list: [&#39;a&#39;, &#39;b&#39;, &#39;c&#39;, &#39;d&#39;, &#39;e&#39;, &#39;f&#39;, &#39;g&#39;, &#39;h&#39;, &#39;i&#39;, &#39;j&#39;, &#39;k&#39;, &#39;l&#39;, &#39;m&#39;, &#39;n&#39;]
Expected Output: [[&#39;a&#39;, &#39;d&#39;, &#39;g&#39;, &#39;j&#39;, &#39;m&#39;], [&#39;b&#39;, &#39;e&#39;, &#39;h&#39;, &#39;k&#39;, &#39;n&#39;], [&#39;c&#39;, &#39;f&#39;, &#39;i&#39;, &#39;l&#39;]]
"""

new_list=[]
l=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']
l0=l[::3]
l1=l[1::3]
l2=l[2::3]
new_list.append(l0)
new_list.append(l1)
new_list.append(l2)
print("new_list :",new_list)

"""WRITE PROGRAM TO CYCLE LIST FOR N USER GIVEN TIMES
INPUT:[11,22,33,44,55]
N=2
[22,33,44,55,11]
[33,44,55,11,22]
"""

l=[11,22,33,44,55] 
n=2
#n=int(input("Enter number of time rotation :"))
for i in range(n+1):
  l0=l[i:]+l[:i]
print("After rotating :",l0)



"""Write a Python program to remove duplicates from a list of lists.
Sample list : [[10, 20], [40], [30, 56, 25], [10, 20], [33], [40]]
New List : [[10, 20], [30, 56, 25], [33], [40]]
"""

Sample=[[10, 20], [40], [30, 56, 25], [10, 20], [33], [40]]

temp=[]

for i in Sample:
    if i not in temp:
      temp.append(i)

print("temp",temp)

type(l)

"""Write a Python program to decode a run-length encoded given list.
Original encoded list:
[[2, 1], 2, 3, [2, 4], 5, 1]
Decode a run-length encoded said list:
[1, 1, 2, 3, 4, 4, 5, 1]
"""



"""ASSIGNMENT 3

Question 1- Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.
Sample value of n is 5
Expected Result : 615
"""

n=int(input("Enter a Integer:"))
a=n+n*11+n*111
print(a)

"""Question 2- Write a Python program to get the volume of a sphere with radius 6  """

import math
r=6
V=(4/3)*(math.pi)*r**3
print("Volume of Sphere is:",V)

"""Question 3- Write a Python program to calculate the sum of three given numbers, if the values are equal then return three
times of their sum.
"""

a=float(input("Enter 1st Num:"))
b=float(input("Enter 2nd Num:"))
c=float(input("Enter 3rd Num:"))
sum=a+b+c
print("Sum of three numbers:",sum)
if a==b==c:
  print("Three Times of Sum:",sum*3)
else:
  print("Not Equal")

"""Question 4- Write a Python program to count the number 4 in a given list."""

l=[1,2,3,4,4,5,6,2,4,5,4]
print("Count of 4:",l.count(4))

"""Question 5- Write a Python program to check whether a specified value is contained in a group of values.
Test Data :
3 -&gt; [1, 5, 8, 3] : True
-1 -&gt; [1, 5, 8, 3] : False
"""

l=[1,5,3,8]
n=int(input("Enter the number"))
if l.count(n)==True:
  print("True")
else:
  print("False")

"""Question 6- Write a Python program to solve (x + y) * (x + y)"""

x=int(input("Enter x:"))
y=int(input("Enter y:"))
m=(x+y)*(x+y)
print("The Output of this program is:",m)

"""Test Data : x = 4, y = 3
Expected Output : (4 + 3) ^ 2) = 49
"""

x=int(input("Enter x:"))
y=int(input("Enter y:"))
m=(x+y)**2
print("The Output of this program is:",m)

"""Question 8-Write a Python program to compute the future value of a specified principal amount, rate of interest, and a
number of years.
Test Data : amt = 10000, int = 3.5, years = 7
Expected Output : 12722.79
"""

amt=10000
it=3.5
y=7
Fv=amt*((1+(0.01*it)) ** y) # FV=P((1+r)^t)
print("Future Value:",Fv)

"""Question 9- Write a python program to find the sum of the first n positive integers."""

sum=0
while True:
  data=int(input("Enter the Data:"))
  if data<0:
    break
  sum+=data
print("Sum of n Positive Integers:",sum)

"""Question 10- Write a Python program to convert the distance (in feet) to inches, yards, and miles. 1feet=12 inch, 1feet=0.33 yards ,1 feet=0.000189394 miles"""

dist=float(input("Enter the Distance in feet:"))
inch=dist*12
yard=dist*0.33
miles=dist*0.000189394
print("Distance in inches:",inch)
print("Distance in yard:",yard)
print("Distance in miles:",miles)