# -*- coding: utf-8 -*-
"""Bank Account.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18olP1VFK4cGnWWGQUNnvW_oqVhFANAL8
"""

"This is Bank Account Program"

# Bank Acoount Creation
class BankAcc:
  AccNo=202100
  def __init__(self,n,b):
        BankAcc.AccNo+=1
        self.AccNo=BankAcc.AccNo
        print("one Account created---now total Accounts:",BankAcc.AccNo)
        self.name=n
        self.Balance=b
  def Details(self):
    print("My name:",self.name,"and Balance is:",self.Balance)
  def Deposite(self):
    self.Deposite=int(input("Enter the amount to deposite:"))
    if self.Deposite>0:
      print("Deposited")
      self.Balance+=self.Deposite
    else:
      print("Invalid Amount")
    print("Total Balance:",self.Balance)
  def Withdrawels(self):
    self.Withdrawels=int(input("Enter the amount to Withdraw:"))
    if self.Balance>=1000:
      if self.Balance-self.Withdrawels>=1000:
        self.Balance-=self.Withdrawels
        print("Withdraw Ok")
      else:
        print("Error in Maintaining Minimum Balance")
      print("Total Balance:",self.Balance)
  def Total_Balance(self):
    print("Total Balance:",self.Balance)

# Users Creating Account
a1=BankAcc("MKP",10000)
a2=BankAcc("UVJ",20000)
a3=BankAcc("SMP",30000)
a4=BankAcc("STF",40000)
a5=BankAcc("PRJ",60000)
a6=BankAcc("NRR",1000)
a7=BankAcc("MLT",50000)
a8=BankAcc("JKP",30000)
a9=BankAcc("AAA",10000)
a10=BankAcc("RAJ",5000)

# ATM Machine
dt={202101:a1,202102:a2,202103:a3,202104:a4,202105:a5,202106:a6,202107:a7,202108:a8,202109:a9,202110:a10}
while True:
  AccNo=int(input("Enter Account Number:"))
  if AccNo>=202100 and AccNo<=202110:
    if AccNo in dt:
      a=int(input("Enter Choice: 1)Balance Check 2) Deposit 3) Withdrawel "))
      if a==1:
        dt[AccNo].Total_Balance()
        break
      elif a==2:
        dt[AccNo].Deposite()
        break
      elif a==3:
        dt[AccNo].Withdrawels()
        break
  else:
    print("Invalid Account Number")
    break
  break